### ISSUE TITLE
[Bug]: Cannot login to extension after updating to 10.12.0

### ISSUE THREAD

**Issue by 0xfoobar** [MetaMask/metamask-extension#14282]
### Describe the bug

<img width="338" alt="Screen Shot 2022-03-30 at 5 47 34 PM" src="https://user-images.githubusercontent.com/83792390/160936558-3967e31d-729b-45c0-bdb8-744a83bcec92.png">

I updated my chrome extension and tried to login with my password, as I've done hundreds of time before. But got the error `this.str.charCodeAt is not a function`

### Steps to reproduce

1. Update to 10.12.0

### Version

10.12.0

### Browser

Chrome

### Operating system

MacOS

**Comment by chendatony31** [comment]
Same here

**Comment by the-nuvish** [comment]
any solution yet?

**Comment by romon029** [comment]
Same

**Comment by farhad2161** [comment]
same and shame

**Comment by the-nuvish** [comment]
i imported my wallet to Brave and now it's working

**Comment by chendatony31** [comment]
Fixed at `10.12.1`

**Comment by Gudahtt** [comment]
Sorry for the inconvenience, this has now been fixed. v10.12.1 or above should work correctly.

**Comment by kiidfreak** [comment]
Hello @Gudahtt I'm Experiencing the same problem

**Comment by kiidfreak** [comment]
![Screenshot (245)](https://user-images.githubusercontent.com/59394569/165730192-b7d61152-80a1-4ff4-8232-aefd3355e268.png)
