### ISSUE TITLE
New chainId validations break evm chains that do not implement chain_id method

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#9683]
TomoChain in particular does not support the chain_id method, and so version 8.1 breaks support for it, since we validate the user-entered value against the RPC.

This means TomoChain is currently broken on Firefox, and those users should use Chrome.

Proposed solution: If a user enters a custom RPC for a network that does not implement chain_id, we should trust the chain_id value entered by the user (ideally indicating to the user if it duplicates any known networks).

**Comment by chrisfranko** [comment]
Not only that but FireFox is breaking as well on chains behind nginx. It works if I use http-proxy to serve the proxy pass.

<img width="345" alt="Screen Shot 2020-10-26 at 7 55 18 PM" src="https://user-images.githubusercontent.com/3543217/97240642-2e6fb100-17c5-11eb-8c4b-f55659c65fdc.png">

You can check the node with curl.

```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":67}' https://node.expanse.tech
```

**Comment by afmfe-iul** [comment]
Local chains running on Ganache CLI are also breaking after upgrading Metamask to 8.1.3.
When adding custom networks to Metamask we started receiving the error `The endpoint returned a different chain ID: 0x539`. 
In case it's helpful for anyone, the issue was caused by Ganache chain_id defaulting to [1337](https://github.com/trufflesuite/ganache-core/issues/441). Upgrading Ganache CLI to [v6.11.0](https://github.com/trufflesuite/ganache-cli/releases/tag/v6.11.0) and passing the option `--chainId` with the correct value fixed the problem.

**Comment by rattrap** [comment]
Same problem when trying to connect to a https://www.kaleido.io/ node. They use basic auth.
`Could not fetch chain ID. Is your RPC URL correct?`

**Comment by wbt** [comment]
I'm also seeing this break a dapp running with geth on a custom chainID even when the entered chain id matches the --networkid parameter to geth which also matches the config.chainId property in the genesis block.  The error is "Could not fetch chain ID. Is your RPC URL correct?" Yes, it's the same RPC URL that worked with prior versions.

Forcing out breaking changes on all users without making it easy to revert to a version preceding the breaking changes is not cool.

**Comment by Hauleraway** [comment]
@afmfe-iul I am getting the same error when trying to create a Custom RPC in Metamask. I am unable to get the right chainId

**Comment by chrisfranko** [comment]
So, for an update, i figured out that cors wasnt set properly. I had cors on nginx AND the geth/gexp nodes. Once cors was set properly everything began working. Which is interesting that firefox was strict with cors but chrome was relaxed haha.

**Comment by wbt** [comment]
In the dapp I observed, it was because the node being connected to was running too old a version of geth, before eth_chainId.  Still, with issues like this and #9421, I maintain that forcing out breaking changes on all users without making it easy to revert to a version preceding the breaking changes is not cool.

**Comment by danfinlay** [comment]
Deleted some outdated comments that touched unrelated issues.

**Comment by Myu-Unix** [comment]
So my fully sinced (local) Geth 1.10.2 node cannot be plugged to Metamask anymore as a custom RPC ? Is there any workarounds ?

**Comment by wbt** [comment]
@Myu-Unix You might consider making a full backup and then updating the Geth executable files, then starting up with the same data directory.

**Comment by gorgsenegger** [comment]
Are there any updates on this? I've got the same problem and haven't found a solution.

My local geth node in a private network is running under WSL on Windows 10. I **can** access it without problems from within WSL as well as using the geth Version for Windows. Network ID and Chain ID are both 1000.

When I try this within MetaMask in my browser, I keep getting the _"Could not fetch chain ID. Is your RPC URL correct?"_ error.

**Comment by wbt** [comment]
@gorgsenegger Run a later version of geth.

**Comment by gorgsenegger** [comment]
@wbt - I'm using version 1.10.3-stable on both Windows and Ubuntu WSL

**Comment by rekmarks** [comment]
We've really voted with our feet, here.

You've been unable to use an EVM chain that doesn't support `eth_chainId` during the ~10 months since this issue was created, and we have no plans to change this in the future.

I will now close this issue.
