### ISSUE TITLE
[non-blocker][Bug]: Onboarding V2 - Error: Unable to find value of key "welcomeToMetaMask" for locale "en"

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#16958]
### Describe the bug

https://user-images.githubusercontent.com/53189696/207701778-f6b53fcc-785e-4d2e-8ac6-434a95cdb776.mov

### Steps to reproduce

1. Install the extension with ONBOARDING_V2 enabled
2. Change the language on the welcome page from English to Persian
3. Change the language on the welcome page from Persian to English

### Error messages or log output

```shell
sentry-install.js:76 Error: Unable to find value of key "welcomeToMetaMask" for locale "en"
  at n.getMessage (common-7.js:1:59543)
  at ui-6.js:1:330194
  at n.default (ui-8.js:1:185687)
  at ha (ui-3.js:1:59903)
  at Qa (ui-3.js:1:68113)
  at Cu (ui-3.js:1:105834)
  at El (ui-3.js:1:90577)
  at bl (ui-3.js:1:90502)
  at fl (ui-3.js:1:87850)
  at ui-3.js:1:46308
  at n.unstable_runWithPriority (ui-3.js:26:73352)
  at Ko (ui-3.js:1:46017)
  at Zo (ui-3.js:1:46253)
  at Jo (ui-3.js:1:46188)
  at pl (ui-3.js:1:88142)
  at Object.notify (ui-3.js:1:203835)
  at t.notifyNestedSubs (ui-3.js:1:203402)
  at t.handleChangeWrapper (ui-3.js:1:203470)
  at y (common-6.js:1:136858)
  at common-6.js:1:133423
  at dispatch (common-6.js:1:135023)
  at common-7.js:1:200254
  at Object.dispatch (common-6.js:1:133414)
  at ui-7.js:1:30081
  at a.<anonymous> (ui-9.js:1:101924)
  at u (common-6.js:3:1144)
  at a.emit (common-6.js:3:1680)
  at s.handleResponse (ui-9.js:1:102418)
  at b (common-1.js:1:21389)
  at a.emit (common-1.js:1:24384)
  at w (common-6.js:1:101609)
  at E (common-6.js:1:101424)
  at _.push (common-6.js:1:102238)
  at e.exports._write (common-6.js:1:45435)
  at _ (common-6.js:1:114654)
  at common-6.js:1:117838
  at y.write (common-6.js:1:117865)
  at e.exports.m (common-6.js:1:106809)
  at b (common-1.js:1:21389)
  at a.emit (common-1.js:1:24384)
  at w (common-6.js:1:101609)
  at E (common-6.js:1:101424)
  at _.push (common-6.js:1:102238)
  at e.exports._onMessage (common-3.js:10:224787)
  at common-3.js:10:224634
```

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by digiwand** [comment]
@PeterYinusa Nice find! This appears to be a current issue when changing the language from a right-to-left language ("fa") to a left-to-right language ("en"). We will see errors for `en` and warnings for and for other, non-"en", left-to-right languages. The good thing is that the UI/UX eventually fixes itself. This is a non-blocker for v10.24.0. 

The fix for this one should also fix the similar issue found from changing the language in settings.

<img width="1680" alt="Screen Shot 2022-12-16 at 02 12 27" src="https://user-images.githubusercontent.com/20778143/207947045-72254247-7cf5-4e67-88b6-e97bf3eb657f.png">

It appears that the locale of `localeMessages` will be a mismatch from the `currentLocale`.
<img width="1144" alt="Screen Shot 2022-12-16 at 02 04 01" src="https://user-images.githubusercontent.com/20778143/207948415-7a7aa70a-4690-4f2e-809e-49946636ca85.png">

I will put aside fixing this to work on other v10.24.0 issues since I believe this is not a blocker.

**Comment by PeterYinusa** [comment]
> @PeterYinusa Nice find! This appears to be a current issue when changing the language from a right-to-left language ("fa") to a left-to-right language ("en"). We will see errors for `en` and warnings for and for other, non-"en", left-to-right languages. The good thing is that the UI/UX eventually fixes itself. This is a non-blocker for v10.24.0.
> 
> The fix for this one should also fix the similar issue found from changing the language in settings.
> 
> <img alt="Screen Shot 2022-12-16 at 02 12 27" width="1680" src="https://user-images.githubusercontent.com/20778143/207947045-72254247-7cf5-4e67-88b6-e97bf3eb657f.png">
> 
> It appears that the locale of `localeMessages` will be a mismatch from the `currentLocale`. <img alt="Screen Shot 2022-12-16 at 02 04 01" width="1144" src="https://user-images.githubusercontent.com/20778143/207948415-7a7aa70a-4690-4f2e-809e-49946636ca85.png">
> 
> I will put aside fixing this to work on other v10.24.0 issues since I believe this is not a blocker.

Thanks for diving deeper into this one. Sounds like a plan

**Comment by WalletSupportt** [comment]
> ### Describe the bug
> 
> 
> https://user-images.githubusercontent.com/53189696/207701778-f6b53fcc-785e-4d2e-8ac6-434a95cdb776.mov
> 
> 
> 
> ### Steps to reproduce
> 
> 1. Install the extension with ONBOARDING_V2 enabled
> 2. Change the language on the welcome page from English to Persian
> 3. Change the language on the welcome page from Persian to English
> 
> 
> ### Error messages or log output
> 
> ```shell
> sentry-install.js:76 Error: Unable to find value of key "welcomeToMetaMask" for locale "en"
>   at n.getMessage (common-7.js:1:59543)
>   at ui-6.js:1:330194
>   at n.default (ui-8.js:1:185687)
>   at ha (ui-3.js:1:59903)
>   at Qa (ui-3.js:1:68113)
>   at Cu (ui-3.js:1:105834)
>   at El (ui-3.js:1:90577)
>   at bl (ui-3.js:1:90502)
>   at fl (ui-3.js:1:87850)
>   at ui-3.js:1:46308
>   at n.unstable_runWithPriority (ui-3.js:26:73352)
>   at Ko (ui-3.js:1:46017)
>   at Zo (ui-3.js:1:46253)
>   at Jo (ui-3.js:1:46188)
>   at pl (ui-3.js:1:88142)
>   at Object.notify (ui-3.js:1:203835)
>   at t.notifyNestedSubs (ui-3.js:1:203402)
>   at t.handleChangeWrapper (ui-3.js:1:203470)
>   at y (common-6.js:1:136858)
>   at common-6.js:1:133423
>   at dispatch (common-6.js:1:135023)
>   at common-7.js:1:200254
>   at Object.dispatch (common-6.js:1:133414)
>   at ui-7.js:1:30081
>   at a.<anonymous> (ui-9.js:1:101924)
>   at u (common-6.js:3:1144)
>   at a.emit (common-6.js:3:1680)
>   at s.handleResponse (ui-9.js:1:102418)
>   at b (common-1.js:1:21389)
>   at a.emit (common-1.js:1:24384)
>   at w (common-6.js:1:101609)
>   at E (common-6.js:1:101424)
>   at _.push (common-6.js:1:102238)
>   at e.exports._write (common-6.js:1:45435)
>   at _ (common-6.js:1:114654)
>   at common-6.js:1:117838
>   at y.write (common-6.js:1:117865)
>   at e.exports.m (common-6.js:1:106809)
>   at b (common-1.js:1:21389)
>   at a.emit (common-1.js:1:24384)
>   at w (common-6.js:1:101609)
>   at E (common-6.js:1:101424)
>   at _.push (common-6.js:1:102238)
>   at e.exports._onMessage (common-3.js:10:224787)
>   at common-3.js:10:224634
> ```
> 
> 
> ### Version
> 
> 10.24.0
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> MacOS
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
