### ISSUE TITLE
[Bug]: Error fetching quotes:  TypeError: Cannot read properties of undefined (reading 'gas')

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#18580]
### Describe the bug

https://user-images.githubusercontent.com/53189696/231844613-4c8924c4-dfba-4bab-90d3-e20c6a7d8fb2.mov

### Steps to reproduce

1. Log in to the extension
2. switch network to optimism
3. Click the swap button
4. enter an ETH amount and wait for the `/gasPrices` API to respond

### Error messages or log output

```shell
swaps.js:837 Error fetching quotes:  TypeError: Cannot read properties of undefined (reading 'gas')
  at buildUnserializedTransaction.js:10:31
  at r.default (buildUnserializedTransaction.js:31:20)
  at r.default (fetchEstimatedL1Fee.js:44:5)
  at background-3.js:10:118902
  at Array.map (<anonymous>)
  at c.default.fetchAndSetQuotes (background-3.js:10:118849)
  at async x.<anonymous> (background-4.js:1:118610)
(
```

### Version

10.29

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by danjm** [comment]
I can't figure out how yet, but surely this was introduced by https://github.com/MetaMask/metamask-extension/commit/f92e463a0f2

So I have assigned this to the extension platform team for now
