### ISSUE TITLE
Bug web3 with vuex in metamask version 7.7.0

### ISSUE THREAD

**Issue by tranchien2002** [MetaMask/metamask-extension#7640]
**Describe the bug**
I am using Vuejs + vuex to integrate with metamask. In my case, i want store web3 object to vuex's state, it work well in 7.6 but get error when i update metamask version:

**inpage.js:1 Uncaught (in promise) Error: Invalid JSON RPC response: undefined**

**Uncaught TypeError: e is not a function**

The error message is completely vague so it is difficult to fix it.

**Screenshots**
![image](https://user-images.githubusercontent.com/26900321/70119404-c8ee6f80-169c-11ea-85ed-19469120092c.png)

**Browser details (please complete the following information):**
 - OS: Ununtu 18.04
 - Browser Chrome
 - MetaMask Version 7.7.0
**Additional context**

**Comment by Gudahtt** [comment]
Thanks for the report! Are you still experiencing this issue with the latest version of MetaMask?

I'm going to close this for now, as I think you're trying to save the `window.web3` object to state, and that's not advised because it's not serializable. So this is a bug in your site, and you need to find some alternate means of holding onto that reference. But if I'm mistaken and you meant something else, please let me know!
