### PR TITLE
chore: popover issue with preview builds

### PR DESCRIPTION
**Pull request by georgewrmarshall**
## **Description**

**This PR tests whether reverting the LavaMoat patch fixes the popover positioning issue in production builds.**

This PR reverts commit `ed02ac23e86fc3a20336901a2bef52365cdd6bb1` ("fix: lavamoat patch (#36628)") to test our theory that the LavaMoat policy changes are causing ALL popover components to fail to anchor properly to their reference elements in GitHub Actions builds.

**The Problem:**
- All popovers work correctly in local development and 13.5.0 branch builds
- All popovers fail to position correctly in GitHub Actions production builds on main branch
- Console errors show "TypeError: e is not a function" indicating @popperjs/core functions are blocked

**The Theory:**
The LavaMoat policy changes in the reverted commit are preventing @popperjs/core from accessing necessary DOM positioning APIs, causing popovers to float unanchored instead of positioning relative to their anchor elements.

**This PR will prove/disprove the theory by:**
1. Reverting the problematic LavaMoat changes
2. Testing if popovers work correctly in GitHub Actions builds
3. Determining if this is the root cause

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/36909?quickstart=1)

## **Changelog**

CHANGELOG entry: null

## **Related issues**

Tests fix for popover positioning issue affecting ALL popover components in production builds.

## **Manual testing steps**

1. Wait for GitHub Actions to build this PR
2. Download the built extension artifact 
3. Load the extension in browser
4. Test popover positioning:
   - Click the account menu (top-right)
   - Click the global menu (hamburger icon)
   - Open network selector
   - Verify popovers anchor correctly to their reference elements

**Expected Result:** If our theory is correct, popovers should position correctly in the GitHub Actions build with the LavaMoat patch reverted.

### **Before (Broken - main branch)**
Popovers float unanchored in GitHub Actions builds due to LavaMoat blocking @popperjs/core

### **After (Testing - this PR)**
Should show popovers correctly anchored if LavaMoat revert fixes the issue

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [ ] I've included tests if applicable (this IS the test)
- [ ] I've documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I've applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by georgewrmarshall** [comment]
@metamaskbot update-policies

**Comment by georgewrmarshall** [comment]
@SocketSecurity ignore shallow-clone@0.1.2
