### ISSUE TITLE
No "details" for failed transactions in history

### ISSUE THREAD

**Issue by quezak** [MetaMask/metamask-extension#6316]
**Describe the bug**
Transaction history shows details & etherscan link when a successful transaction is clicked.
If I click a failed transaction, nothing happens. To see the details, I need to manually go to my address's etherscan page and select the failed transaction there. Tested on both Firefox and Chromium.e

**To Reproduce**
1. Do any failing transaction
2. Click on the failed transaction in "History" section of the extension
3. Nothing happens.

**Expected behavior**
I'd expect a "Details" section pop up below the transaction, more or less the same as for successful transactions.

**Screenshots**
![metamask-no-failed-details](https://user-images.githubusercontent.com/666206/54521016-513faf80-496a-11e9-9849-064c08e267ed.png)

**Browser details (please complete the following information):**
 - OS: gentoo linux
 - Browser: Firefox 65.0, Chromium 72.0.3626.28-r1
 - MetaMask Version 6.2.2

**Comment by ContemporaryAnarchy** [comment]
Working on this now, recommended by @kumavis

**Comment by ContemporaryAnarchy** [comment]
Reproduced with V6.2.2 on latest Chrome & Firefox 65. Seems to be working fine however with latest V6.3.0 on Chrome

**Comment by kumavis** [comment]
Verified working on 6.3.0

**Comment by krungle-mataman** [comment]
Hello,

i got the same error with
OS: Windows
Browser: Chrome 75.0.xx
Metamask: 6.7.3

and i don't know if it is still an open-issue ?

**Comment by krungle-mataman** [comment]
Here just something internal concerning the eventid:

{exception: {values: [{stacktrace: {,…}, type: "TypeError", value: "t is not a function"}],…},…}
breadcrumbs: [{timestamp: 1563882539.241, category: "ui.click",…},…]
event_id: "85c4378846b046459d347c23ef808e35"
exception: {values: [{stacktrace: {,…}, type: "TypeError", value: "t is not a function"}],…}
mechanism: {data: {function: "addEventListener", handler: "bound dispatchEvent", target: "EventTarget"},…}
data: {function: "addEventListener", handler: "bound dispatchEvent", target: "EventTarget"}
handled: true
type: "instrument"
